# READ MORE ABOUT READABILITY PARSER HERE: https://www.readability.com/developers/api
# TO GET YOUR READABILITY PARSER KEY SIGN UP TO READABILITY AND GRAB THE KEY HERE: https://www.readability.com/settings/account
readability:
    parser api token: XXX # REPLACE ME

executables:
    # INSTALL WITH `npm install electron-pdf -g`
    electron path: /XXX/XXX/electron-pdf # REPLACE ME
    # FIND INSTALLERS FOR PANDOC AT `http://pandoc.org/installing.html`
    pandoc: /XXX/XXX/pandoc # REPLACE ME
    # FIND INSTALLERS FOR KINDLEGEN AT `https://www.amazon.com/gp/feature.html?docId=1000765211`
    kindlegen: /XXX/XXX/kindlegen # REPLACE ME

# ADD AN EMAIL ACCOUNT HERE TO SEND MOBI BOOKS STRAIGHT TO KINDLE
# ADD YOUR EMAIL ADDRESS TO THE LIST OF ADDRESS THAT CAN SEND CONTENT TO YOUR KINDLE HERE: https://www.amazon.co.uk/mn/dcw/myx.html
email:
    smtp_server: smtp.gmail.com
    smtp_port: 465
    smtp_login: XXX
    user_email: XXX
    # YOU CAN LIST MORE THAN ONE KINDLE ADDRESS TO SEND TO MULTIPLE DEVICES
    kindle_emails:  
        - XXX
    smtp_password: "*FQGAsxThDo7DGxycDZYFraUYt,p[6emZNNxdUu"

logging settings:
    formatters:
        file_style:
            format: '* %(asctime)s - %(name)s - %(levelname)s (%(pathname)s > %(funcName)s > %(lineno)d) - %(message)s  '
            datefmt: '%Y/%m/%d %H:%M:%S'
        console_style:
            format: '* %(asctime)s - %(levelname)s: %(pathname)s:%(funcName)s:%(lineno)d > %(message)s'
            datefmt: '%H:%M:%S'
        html_style:
            format: '<div id="row" class="%(levelname)s"><span class="date">%(asctime)s</span>   <span class="label">file:</span><span class="filename">%(filename)s</span>   <span class="label">method:</span><span class="funcName">%(funcName)s</span>   <span class="label">line#:</span><span class="lineno">%(lineno)d</span> <span class="pathname">%(pathname)s</span>  <div class="right"><span class="message">%(message)s</span><span class="levelname">%(levelname)s</span></div></div>'
            datefmt: '%Y-%m-%d <span class= "time">%H:%M <span class= "seconds">%Ss</span></span>'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: console_style
            stream: ext://sys.stdout
        file:
            class: logging.handlers.GroupWriteRotatingFileHandler
            level: WARNING
            formatter: file_style
            filename: /Users/Dave/.config/polyglot/polyglot.log
            mode: w+
            maxBytes: 102400
            backupCount: 1
    root:
        level: ERROR
        handlers: [file,console]
